name: test
on: push
jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x64]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake -target ${{ matrix.arch }}
